# Serviço do Localstack para utilizar em ambiente de desenvolvimento
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: shotit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack
          ports:
            - containerPort: 4566
          env:
            - name: DISABLE_CORS_CHECKS
              value: "1"
            - name: EXTRA_CORS_ALLOWED_ORIGINS
              value: "http://localhost:5173"
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: shotit
spec:
  selector:
    app: localstack
  ports:
    - protocol: TCP
      port: 4566
      targetPort: 4566
